#!/bin/sh

# Define the Roblox installation path
robloxPath="/Applications/Roblox.app"

# Check if Roblox is installed in the default location
if [ ! -d "$robloxPath" ]; then
  # If not, check in the user's home directory
  robloxPath="$HOME$robloxPath"

  if [ ! -d "$robloxPath" ]; then
    echo "Roblox installation folder couldn't be found."
    exit 1
  fi
fi

# Define the ClientSettings path
clientSettingsPath="$robloxPath/Contents/MacOS/ClientSettings"

# Create the ClientSettings directory if it doesn't exist
if [ ! -d "$clientSettingsPath" ]; then
  echo "Creating ClientSettings directory..."
  mkdir -p "$clientSettingsPath"
fi

# Ask the user if they want to use the Vulkan renderer
echo "Do you want to use the Vulkan renderer? This will remove the FPS cap completely, but might break Roblox if you use an external monitor. (yes/no): "
read useVulkan

# Generate the JSON content based on user input
case $useVulkan in
  yes)
    clientSettings='{
 "DFFlagDebugPauseVoxelizer": "True",
 "DFFlagDebugPerfMode": "True",
 "DFFlagDebugRenderForceTechnologyVoxel": "True",
 "DFIntCullFactorPixelThresholdShadowMapHighQuality": "2147483647",
 "DFIntCullFactorPixelThresholdShadowMapLowQuality": "2147483647",
 "DFIntMaxFrameBufferSize": "3",
 "DFIntPerformanceControlTextureQualityBestUtility": "-1",
 "DFIntTaskSchedulerTargetFps": "666",
 "FFlagDebugDisplayFPS": "True",
 "FFlagDebugGraphicsDisableMetal": "True",
 "FFlagDebugGraphicsPreferVulkan": "True",
 "FFlagDebugSkyGray": "True",
 "FIntDebugTextureManagerSkipMips": "3",
 "FIntRenderShadowIntensity": "0",
 "FIntTerrainArraySliceSize": "0",
 "FLogNetwork": "7"
}'
    ;;

  no)
    clientSettings='{
 "DFFlagDebugPauseVoxelizer": "True",
 "DFFlagDebugPerfMode": "True",
 "DFFlagDebugRenderForceTechnologyVoxel": "True",
 "DFIntCullFactorPixelThresholdShadowMapHighQuality": "2147483647",
 "DFIntCullFactorPixelThresholdShadowMapLowQuality": "2147483647",
 "DFIntMaxFrameBufferSize": "3",
 "DFIntPerformanceControlTextureQualityBestUtility": "-1",
 "DFIntTaskSchedulerTargetFps": "666",
 "FFlagDebugDisplayFPS": "True",
 "FFlagDebugSkyGray": "True",
 "FIntDebugTextureManagerSkipMips": "3",
 "FIntRenderShadowIntensity": "0",
 "FIntTerrainArraySliceSize": "0",
 "FLogNetwork": "7"
}'
    ;;

  *)
    echo "Unknown option. Please run the script again and type 'yes' or 'no'."
    exit 1
    ;;
esac

# Write the JSON content to the ClientAppSettings.json file
echo "$clientSettings" > "$clientSettingsPath/ClientAppSettings.json"

# Check if the file was created successfully
if [ -f "$clientSettingsPath/ClientAppSettings.json" ]; then
  echo "The FPS unlocker has been installed in $robloxPath."
else
  echo "Failed to create ClientAppSettings.json."
  exit 1
fi
